import {
  Activity, Dumbbell, Footprints, Bike, Trophy, Mountain, MountainSnow,
  Music, Film, Tv, Gamepad2, BookOpen, Mic2, Sparkles, Headphones, Mic,
  Camera, Palette, PenTool, PenLine, Scissors, Hammer,
  ChefHat, Cake, Wine, Coffee, Beer, Utensils, Globe,
  Plane, Umbrella, Tent, Map, Car,
  Dog, Cat, PawPrint,
  Shirt, Flame, Heart, Leaf, Flower2, HeartHandshake,
  Laptop, Rocket, Bitcoin, Bot,
  PartyPopper, Croissant, Users, Network,
  MoonStar, Sun, Languages, Landmark, FlaskConical, Star,
  Dribbble, Waves, Clapperboard, MonitorPlay, Trees
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const getInterestIcon = (interest: string): LucideIcon => {
  const map: Record<string, LucideIcon> = {
    'Fútbol': Dribbble,
    'Baloncesto': Dribbble,
    'Natación': Waves,
    'Yoga': Activity,
    'Gimnasio': Dumbbell,
    'Running': Footprints,
    'Ciclismo': Bike,
    'Tenis': Trophy,
    'Senderismo': Trees,
    'Escalada': MountainSnow,
    'Música': Music,
    'Películas': Film,
    'Series': Tv,
    'Videojuegos': Gamepad2,
    'Lectura': BookOpen,
    'Teatro': Clapperboard,
    'Conciertos': Mic2,
    'Anime': Sparkles,
    'Podcasts': Headphones,
    'Stand-up': Mic,
    'Fotografía': Camera,
    'Pintura': Palette,
    'Diseño': PenTool,
    'Escritura': PenLine,
    'Manualidades': Scissors,
    'Escultura': Hammer,
    'Cocina': ChefHat,
    'Repostería': Cake,
    'Vino': Wine,
    'Café': Coffee,
    'Cerveza artesanal': Beer,
    'Restaurantes': Utensils,
    'Comida internacional': Globe,
    'Viajes': Plane,
    'Playa': Umbrella,
    'Montaña': Mountain,
    'Camping': Tent,
    'Mochilero': Map,
    'Road trips': Car,
    'Perros': Dog,
    'Gatos': Cat,
    'Animales': PawPrint,
    'Moda': Shirt,
    'Meditación': Flame,
    'Bienestar': Heart,
    'Naturaleza': Leaf,
    'Jardinería': Flower2,
    'Voluntariado': HeartHandshake,
    'Tecnología': Laptop,
    'Startups': Rocket,
    'Criptomonedas': Bitcoin,
    'Inteligencia Artificial': Bot,
    'Fiestas': PartyPopper,
    'Baile': Music,
    'Karaoke': Mic2,
    'Brunch': Croissant,
    'Cenas grupales': Users,
    'Networking': Network,
    'Astrología': MoonStar,
    'Tarot': Sun,
    'Idiomas': Languages,
    'Historia': Landmark,
    'Ciencia': FlaskConical,
    'Política': Landmark,
  };

  return map[interest] || Star;
};
